---------------------------------------------------------------------------------
-- AGGREGATIONS AND GROUP BY STATEMENT
---------------------------------------------------------------------------------

-- 1. How many sales did we make in each continent?
SELECT
    Continent,
    COUNT(*) AS Total_Sales
FROM [pc_database].[dbo].[pc_data_v2]
GROUP BY Continent;

-- 2. What is the total sales value for each payment method?
SELECT
    Payment_Method,
    SUM(Sale_Price) AS Total_Sales_Value
FROM [pc_database].[dbo].[pc_data_v2]
GROUP BY Payment_Method;

-- 3. How many PCs did we sell per brand (make)?
SELECT
    PC_Make,
    COUNT(*) AS PCs_Sold
FROM [pc_database].[dbo].[pc_data_v2]
GROUP BY PC_Make;

-- 4. What is the total discount we gave out per sales person?
SELECT
    Sales_Person_Name,
    SUM(Discount_Amount) AS Total_Discount
FROM [pc_database].[dbo].[pc_data_v2]
GROUP BY Sales_Person_Name;

-- 5. How many sales came through each channel (Online vs Offline)?
SELECT
    Channel,
    COUNT(*) AS Total_Sales
FROM [pc_database].[dbo].[pc_data_v2]
GROUP BY Channel;

ALTER TABLE [pc_database].[dbo].[pc_data_v2]
ALTER COLUMN Cost_of_Repairs INT;

-- 6. What is the total cost of repairs per department?
SELECT
    Sales_Person_Department,
    SUM(Cost_of_Repairs) AS Total_Repair_Cost
FROM [pc_database].[dbo].[pc_data_v2]
GROUP BY Sales_Person_Department;

-- 7. How many orders fall into each priority level?
SELECT
    Priority,
    COUNT(*) AS Total_Orders
FROM [pc_database].[dbo].[pc_data_v2]
GROUP BY Priority;

-- 8. What is the total sale price generated by each shop?
SELECT
    Shop_Name,
    SUM(Sale_Price) AS Total_Sale_Price
FROM [pc_database].[dbo].[pc_data_v2]
GROUP BY Shop_Name;

-- 9. How many PCs were sold for each storage type (SSD vs HDD)?
SELECT
    Storage_Type,
    COUNT(*) AS PCs_Sold
FROM [pc_database].[dbo].[pc_data_v2]
GROUP BY Storage_Type;

-- 10. What is the total finance amount taken up per country/state?
SELECT
    Country_or_State,
    SUM(Finance_Amount) AS Total_Finance_Amount
FROM [pc_database].[dbo].[pc_data_v2]
GROUP BY Country_or_State;